# Generated by Django 3.0.7 on 2021-02-10 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='permanent_aadhar_no',
            new_name='contact_address_proof_aadhar_no',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='permanent_contact_person_name',
            new_name='contact_address_proof_contact_person_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='permanent_contact_person_no',
            new_name='contact_address_proof_contact_person_no',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='permanent_email',
            new_name='contact_address_proof_email',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='permanent_mobile_one',
            new_name='contact_address_proof_mobile_one',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='permanent_mobile_two',
            new_name='contact_address_proof_mobile_two',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='permanent_pan',
            new_name='contact_address_proof_pan',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='permanent_phone',
            new_name='contact_address_proof_phone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='permanent_pin_code',
        ),
    ]
