# Generated by Django 3.0.7 on 2021-02-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20210210_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.CharField(max_length=250),
        ),
    ]
