# Generated by Django 3.0.7 on 2021-02-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20210210_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='employee',
            name='site',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_man_no_int',
            field=models.CharField(max_length=250),
        ),
    ]
