# Generated by Django 3.0.8 on 2020-07-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('master_add', models.BooleanField(default=False)),
                ('master_delete', models.BooleanField(default=False)),
                ('master_update', models.BooleanField(default=False)),
                ('master_list', models.BooleanField(default=True)),
                ('user_add', models.BooleanField(default=False)),
                ('user_delete', models.BooleanField(default=False)),
                ('user_update', models.BooleanField(default=False)),
                ('user_list', models.BooleanField(default=True)),
                ('org_add', models.BooleanField(default=False)),
                ('org_delete', models.BooleanField(default=False)),
                ('org_update', models.BooleanField(default=False)),
                ('org_list', models.BooleanField(default=True)),
                ('branch_add', models.BooleanField(default=False)),
                ('branch_delete', models.BooleanField(default=False)),
                ('branch_update', models.BooleanField(default=False)),
                ('branch_list', models.BooleanField(default=True)),
                ('work_order_add', models.BooleanField(default=False)),
                ('work_order_delete', models.BooleanField(default=False)),
                ('work_order_update', models.BooleanField(default=False)),
                ('work_order_list', models.BooleanField(default=True)),
                ('billing_add', models.BooleanField(default=False)),
                ('billing_delete', models.BooleanField(default=False)),
                ('billing_update', models.BooleanField(default=False)),
                ('billing_list', models.BooleanField(default=True)),
                ('payment_add', models.BooleanField(default=False)),
                ('payment_delete', models.BooleanField(default=False)),
                ('payment_update', models.BooleanField(default=False)),
                ('payment_list', models.BooleanField(default=True)),
            ],
        ),
    ]
