# Generated by Django 3.0.8 on 2020-07-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_group_id', models.IntegerField()),
                ('head_org_user', models.BooleanField(default=False)),
                ('head_branch_user', models.BooleanField(default=False)),
                ('super_user', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
