# Generated by Django 3.0.8 on 2020-07-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_group', '0002_userpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='branch_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='org_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
