# Generated by Django 3.0.8 on 2020-07-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_group', '0003_auto_20200703_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
