# Generated by Django 3.0.8 on 2020-07-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PERMISSION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('admin', models.BooleanField(default=False)),
                ('master', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='USERTABLE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(blank=True, max_length=250, null=True)),
                ('password', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('department', models.IntegerField(blank=True, null=True)),
                ('branch', models.IntegerField(blank=True, null=True)),
                ('address_primary', models.TextField(blank=True, null=True)),
                ('address_secondery', models.TextField(blank=True, null=True)),
                ('user_role', models.IntegerField(blank=True, null=True)),
                ('permission', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('state', models.CharField(blank=True, max_length=250, null=True)),
                ('pin', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
