# Generated by Django 3.0.8 on 2020-07-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_auto_20200725_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='superuser',
            field=models.BooleanField(default=False),
        ),
    ]
