# Generated by Django 3.0.8 on 2020-07-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0003_permission_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usertable',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
