# Generated by Django 3.0.8 on 2020-08-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0005_auto_20200825_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='employee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
