# Generated by Django 3.0.8 on 2020-08-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0006_usertable_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='city',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='state',
        ),
        migrations.AlterField(
            model_name='usertable',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
