# Generated by Django 3.0.8 on 2020-08-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0007_auto_20200825_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
