# Generated by Django 3.0.8 on 2020-08-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0008_permission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
