# Generated by Django 3.0.8 on 2020-09-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0009_usertable_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='active',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='address_primary',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='address_secondery',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='department',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='name',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='status',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='user_role',
        ),
        migrations.AlterField(
            model_name='usertable',
            name='employee_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
