# Generated by Django 3.0.8 on 2020-09-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0012_auto_20200924_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='grn_edit',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='grn_view',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='job_card_edit',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='job_card_view',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='master_delete',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='master_update',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='master_view',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='pending_request_approve',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='pending_request_list',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='pending_request_view',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='premitive_maintaince_add',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='premitive_maintaince_edit',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='premitive_maintaince_view',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='purchase_order_approve',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='purchase_order_edit',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='purchase_order_view',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='quality_check_approve',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='quality_check_view',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='report_current_stock_view',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='report_grn_view',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='report_job_card_view',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='report_preventive_view',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='report_purchase_order_view',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='report_request_view',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='report_stock_view',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='report_storeissue_voucher_view',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='request_edit',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='request_list',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='request_view',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='store_issue_voucher_approve',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='store_issue_voucher_view',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='grn_add',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='grn_show',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='job_card_add',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='job_card_show',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='master_add',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='master_edit',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='master_show',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='master_status',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='mis_show',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='preventive_main_add',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='preventive_main_show',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='purchase_enquiry_add',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='purchase_enquiry_show',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='purchase_order_add',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='purchase_order_approval',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='purchase_order_show',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='quality_check',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='quality_check_show',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='reports_show',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='request_add',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='request_approval',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='request_approval_show',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='request_show',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='settings_add',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='settings_edit',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='settings_show',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='settings_status_change',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='store_issue_voucher_add',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='store_issue_voucher_show',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='transfer_add',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='transfer_show',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='work_order_add',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='work_order_show',
        ),
        migrations.AddField(
            model_name='permission',
            name='grn_show',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='job_card_show',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='master_edit',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='master_show',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='master_status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='mis_show',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='preventive_main_add',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='preventive_main_show',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='purchase_enquiry_add',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='purchase_enquiry_show',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='purchase_order_approval',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='purchase_order_show',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='quality_check',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='quality_check_show',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='reports_show',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='request_approval',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='request_approval_show',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='request_show',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='settings_add',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='settings_edit',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='settings_show',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='settings_status_change',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='store_issue_voucher_add',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='store_issue_voucher_show',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='transfer_add',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='transfer_show',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='work_order_add',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='work_order_show',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='grn_add',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='job_card_add',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='master_add',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='purchase_order_add',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='request_add',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
