# Generated by Django 3.0.8 on 2020-09-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0016_usertable_store_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
