# Generated by Django 3.0.8 on 2020-10-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0019_auto_20201005_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='company_details_add',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='company_details_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='company_details_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='entery_challan_add',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='entery_challan_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='job_card_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='job_card_in_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='job_card_out_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='module_permission_add',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='module_permission_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='module_permission_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='request_add_head_branch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='request_approval_main_branch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='return_challan_add',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='return_challan_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='return_challan_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='transfer_add_head_branch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='user_add',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='user_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='user_show',
            field=models.BooleanField(default=False),
        ),
    ]
